version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Entered the pre_build phase...
      - echo Updating yarn GPG keys ...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo Building the Docker image...
      - docker build -t $CONTAINER_NAME:test .
  build:
    commands:
      - IMAGE_TAG=commit-$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - imagedefinitions.json
  secondary-artifacts:
    imagedefinitions:
      files:
        - imagedefinitions.json
