name: Continuous integration
on:
  pull_request:
jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4
        with:
          tflint_version: v0.44.1
      - name: Run TFLint
        run: tflint -f compact
